default: -p prod -b chrome --headless false --logconsole

prod:
  baseUrl: https://www.adobe.com

stage:
  baseUrl: https://www.stage.adobe.com

dev: 
  baseUrl: https://dev--ecc-milo--adobecom.hlx.live